# Generated by Django 5.1.1 on 2025-01-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('carousel_image', models.ImageField(upload_to='Carousel_images')),
            ],
        ),
    ]
