# Generated by Django 5.1.1 on 2025-01-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0006_bannerimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerImage',
        ),
    ]
