# Generated by Django 5.1.1 on 2025-01-24 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purple', '0006_bannerimage'),
        ('vendor', '0002_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offerprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('isofferproduct', models.BooleanField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount Percentage', max_digits=5, null=True)),
                ('Popular_products', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('newarrival', models.BooleanField()),
                ('trending_one', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='purple.category')),
                ('vendors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='vendor.vendors')),
            ],
        ),
    ]
