# Generated by Django 5.1.1 on 2025-01-25 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0003_remove_products_vendor_products_vendors_and_more'),
        ('vendor', '0002_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='vendors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendor.vendors'),
        ),
    ]
