# Generated by Django 5.1.1 on 2025-01-25 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_alter_products_vendors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='vendors',
            new_name='vendor',
        ),
    ]
