# Generated by Django 5.1.1 on 2025-01-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0012_bannerimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='upadated_at',
            new_name='updated_at',
        ),
    ]
