# Generated by Django 5.1.4 on 2025-02-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productsapp", "0014_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductImage",
            new_name="Product_Image",
        ),
    ]
