# Generated by Django 5.1.4 on 2025-02-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productsapp", "0015_rename_productimage_product_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product_Image",
            new_name="ProductImage",
        ),
    ]
