# Generated by Django 5.1.4 on 2025-02-18 05:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productsapp", "0016_rename_product_image_productimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Order",
            new_name="Orders",
        ),
    ]
