# Generated by Django 5.1.4 on 2025-03-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0018_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
