# Generated by Django 5.1.4 on 2025-03-06 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0019_products_category_name'),
        ('purple', '0008_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='purple.subcategories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
